### ISSUE TITLE
IOS 9 have lot of ABAddressBookRef warnings, is there going to be an update for this.

### ISSUE THREAD

**Issue by vickyrappier** [Alterplay/APAddressBook#114] opened 2016-01-09 10:17 UTC
Hi Kiev,

There are many IOS 9 warnings since I updated my project to support IOS 9. Are you planning to make this iOS 9 compatible.

Great library though.

**Comment by belkevich** [comment] 2016-01-13 10:22
Hi,
It's a duplicate of [issue#91](https://github.com/Alterplay/APAddressBook/issues/91)

**Closed by belkevich** 2016-01-13 10:22 UTC
